# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
#
# SPDX-License-Identifier: CC0-1.0

---

name: Copyright & Licenses
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  reuse-me:
    name: REUSE compliance
    runs-on: ubuntu-latest
    steps:
      - uses: dev-build-deploy/reuse-me@v0
        with:
          token: ${{ github.token }}
